### ISSUE TITLE
Cars duplicate spawn menu bug

### ISSUE THREAD

**Issue by Timmyopp** [HumanTree92/esx_advancedvehicleshop#23]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you looked through the Closed Topics?:  Yes
Have you looked through the Wiki?:  Yes
What Version of es_extended are you using?: ExM
Are you using a Pre-Installed ESX?: 
Are you using Essentialmode?: Yes
Are you using OneSync?: Yes
Linux or Windows?: Windows

I have a problem with esx_advancedvehicleshop. Here is a Video which shows the problem
https://vimeo.com/429057422

**Comment by HumanTree92** [comment]
I have read somewhere that this has to do with the cords. Trying changing the cords on lines 204-209 https://github.com/HumanTree92/esx_advancedvehicleshop/blob/master/config.lua#L204

Also checkout https://github.com/ESX-Org/esx_vehicleshop/issues/297

Since you have taken the video from https://github.com/ESX-Org/esx_vehicleshop/issues/305 and you are also having issues with esx_vehicleshop my guess is you installed something wrong. What is it well i don't know. I don't have this issue so there isn't much i can go on. If you provide some errors then maybe i can help.

**Comment by Valkyrionas** [comment]
the issue still continues wether using esx_vehicleshop as well as with esx_advancedvehicleshop....
It would help if anyone knows how to put in a delay of scrolling in the buymenu of a car, the spawn into each other only happens if you lookup the differnet cars on the categories to fast.. I guess due to database ex&import of data... so it might helps a workaround with a cooldown on scrolling (guess a second or two would fix the problem)... would appreciate it if anyone could share a code for this...

**Comment by HumanTree92** [comment]
Thats weird. It must be a client side problem has i can lookup the vehicles on my server super fast & i got 8+ ranks & i don't get it.

**Comment by Valkyrionas** [comment]
may there can be differences on use with es_extended and essentialmode? Im using es_extended 1.2... and of cours no essentialmode

**Comment by HumanTree92** [comment]
Well maybe use esx v1 final. This script only supports esx v1 final and extendedmode.
