### ISSUE TITLE
Blips and marker not showing

### ISSUE THREAD

**Issue by Dokman** [HumanTree92/esx_advancedvehicleshop#34]
**Describe the Bug | A Clear & Concise Description of Bug**
So if i activate Mechanic.Shop = true it have to show the marker but the marker isn't there, why the thread is not drawing it?
i have the exact same problem with the blips

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: 
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: There isn't a wiki
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2 Final
Are you using Essentialmode?: no
Are you using ExtendedMode?: yes
Are you using OneSync?: yes
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
What is your Mechanics name. Check in the DB under jobs. For instance mine says `name = mechanic`

**Comment by Dokman** [comment]
Is at true bit nothing japonés and muy mechanic name is 'mechanic'

**Comment by HumanTree92** [comment]
So are u using ESX V1 Final or ExtendedMode?

**Comment by Dokman** [comment]
ESX V1 Final

**Comment by HumanTree92** [comment]
Any Client side or server side errors. There isn't much to go on. The only thing i can think of atm is your job name is not using mechanic since the only thing that draws the marker is [this line](https://github.com/HumanTree92/esx_advancedvehicleshop/blob/master/client/main.lua#L2048) & [this line](https://github.com/HumanTree92/esx_advancedvehicleshop/blob/master/client/main.lua#L1998) handles the blips [this line](https://github.com/HumanTree92/esx_advancedvehicleshop/blob/master/config.lua#L35) for setting up the blip location. I don't have any issues on my end.

**Comment by Dokman** [comment]
no the problem was that a resource wasn't being satisfied that was esx_licenseshop so now it's working perfect, thanks
